server.port=8080

spring.application.name=technical-debt-analyzer

logging.level.org.springframework=INFO
logging.level.com.yash.tda=DEBUG

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.server.port=8080